### ISSUE TITLE
Extract character name for all slots.

### ISSUE THREAD

**Issue by 1mZ1kk4d0** [jtesta/souls_givifier#3]
I'm in a project and I'm based on things I find on the internet, but unfortunately not everything is rosy, I can't extract the names by offset from the files, because whenever I make a save with another character the offset changes position with the character's nick , I'm doing this in Rust and not in Py so it can be more complicated, my desktop program will list the character information, preferably the name, if you can help me

**Comment by jtesta** [comment]
Sorry to say, but unfortunately I don't have the time to help with general reverse engineering issues.
